# Full End-to-End Python Pipeline 
# Path: .azure-pipelines/templates/full-pipelines/python-azure-functions-end-to-end.yml
# Shared parameters are listed in: .azure-pipelines/templates/_common/common-params.yml

parameters:

# Branch Name Validation

- name: stageName
  type: string
  default: 'EnforceBranchNamingStage'

- name: displayName
  type: string
  default: 'Stage 1 - Enforce Branch Naming (PRs Only)'

- name: jobName
  type: string
  default: 'EnforceBranchNaming'

- name: jobDisplayName
  type: string
  default: 'Validate Branch Naming Convention'

#Build Parameters

- name: pythonVersion
  type: string
  default: '3.11'

- name: requirementsFile
  type: string
  default: 'requirements.txt'

- name: testResultsPath
  type: string
  default: 'junit/test-results.xml'

- name: archiveFileName
  type: string
  default: '$(Build.ArtifactStagingDirectory)/$(Build.SourceVersion).zip'

- name: artifactName
  type: string
  default: 'Build-Drop'

- name: projectPath
  type: string
  default: '.'

#Containarized Application

- name: isContainerized
  type: boolean
  default: false

- name: Dockerfile
  type: string
  default: '**/Dockerfile'

- name: dockerBuildContext
  type: string
  default: '.'

- name: dockerRepository
  type: string
  default: ''

- name: dockerTags
  type: string
  default: 'latest'

# SonarQube parameters
- name: sonarReportArtifactName
  type: string
  default: 'SonarQube-Reports'

- name: sonarQubeServiceConnection
  type: string
  default: ''

- name: sonarQubeProjectKey
  type: string
  default: ''

- name: sonarQubeUrl
  type: string
  default: ''

- name: sonarQubeToken
  type: string
  default: ''
  
- name: branchFilter
  type: string
  default: 'refs/heads/main'

# Wiz parameters
- name: wizClientId
  type: string
  default: ''
  
- name: wizClientSecret
  type: string
  default: ''

- name: wizServiceConnection
  type: string
  default: ''

- name: wizScanPolicies
  type: string
  default: "Fail-on-Medium-Vulns, Default vulnerabilities policy"

- name: wizFailOnSeverity
  type: string
  default: 'Medium'

- name: wizPolicyHitsOnly
  type: boolean
  default: false
    
- name: wizSucceedOnFailures
  type: boolean
  default: false

- name: wizContainerSucceedOnFailures
  type: boolean
  default: false
  
- name: wizContainerimage
  type: string
  default: ''
  
- name: wizContainerpolicyHitsOnly
  type: boolean
  default: true

- name: wizContainerfileHashesScan
  type: boolean
  default: true

 #Tag Release
- name: releasedisplayName
  type: string
  default: 'Stage - Release Tag and Artifact'

- name: releaseBranch
  type: string
  default: 'develop'

- name: releaseType
  type: string
  default: 'patch'

- name: universalFeedNameApp
  type: string
  default: ''

- name: universalPackageName
  type: string
  default: 'App'

# Log Collection
- name: logUniversalFeedName
  type: string
  default: ''

# # Security Scan Configuration
# - name: runPylint
#   type: boolean
#   default: true
# - name: pylintMinScore
#   type: number
#   default: 7.0
# - name: runSonarScan
#   type: boolean
#   default: false
# - name: runTrivyScan
#   type: boolean
#   default: false

# # Deployment Configuration
# - name: deployToAzure
#   type: boolean
#   default: false
# - name: deploymentType
#   type: string
#   default: 'functions'
#   values:
#   - functions
#   - webapp
#   - aks

# Deployment Environment Configuration
- name: environments
  type: object
  default:
  - name: 'dev'
    azureSubscription: ''
    functionAppName: ''
    resourceGroupName: ''


stages:
# ============================================================
# STAGES
# ============================================================

# ------------------------------------------------------------
# Stage 1: Branch Name Validation (PR only)
# ------------------------------------------------------------
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - template: ../stages/validation/branch-name-validation.yml
    parameters:
      stageName: ${{ parameters.stageName }}
      displayName: ${{ parameters.displayName }}
      jobName: ${{ parameters.jobName }}
      jobDisplayName: ${{ parameters.jobDisplayName }}

# ------------------------------------------------------------
# Stage 2: Build & Test (Node.js)
# ------------------------------------------------------------

- template: ../stages/build/python-build-and-test.yml
  parameters:
    pythonVersion: ${{ parameters.pythonVersion }}
    requirementsFile: ${{ parameters.requirementsFile }}
    testResultsPath: ${{ parameters.testResultsPath }}
    archiveFileName: ${{ parameters.archiveFileName }}
    artifactName: ${{ parameters.artifactName }}
    projectPath: ${{ parameters.projectPath }}
    isContainerized: ${{ parameters.isContainerized }}
    # dockerBuildContext: ${{ parameters.dockerBuildContext }}
    # dockerRepository: ${{ parameters.dockerRepository }}
    # Dockerfile: ${{ parameters.Dockerfile }}
    # dockerTags: ${{ parameters.dockerTags }}

# ------------------------------------------------------------
# Stage 3: Run Scan
# ------------------------------------------------------------

- template: ../stages/scan/python-quality-and-security-scan.yml
  parameters:
    pythonVersion: ${{ parameters.pythonVersion }}
    sonarReportArtifactName: ${{ parameters.sonarReportArtifactName }}
    sonarQubeServiceConnection: ${{ parameters.sonarQubeServiceConnection }}
    sonarQubeProjectKey: ${{ parameters.sonarQubeProjectKey }}
    sonarQubeUrl: ${{ parameters.sonarQubeUrl }}
    sonarQubeToken: ${{ parameters.sonarQubeToken }}
    branchFilter: ${{ parameters.branchFilter }}
    wizClientId: ${{ parameters.wizClientId }}
    wizClientSecret: ${{ parameters.wizClientSecret }}
    wizServiceConnection: ${{ parameters.wizServiceConnection }}
    wizScanPolicies: ${{ parameters.wizScanPolicies }}
    wizFailOnSeverity: ${{ parameters.wizFailOnSeverity }}
    wizPolicyHitsOnly: ${{ parameters.wizPolicyHitsOnly }}
    wizSucceedOnFailures: ${{ parameters.wizSucceedOnFailures }}
    wizContainerSucceedOnFailures: ${{ parameters.wizContainerSucceedOnFailures }}
    wizContainerimage: ${{ parameters.wizContainerimage }}
    wizContainerpolicyHitsOnly: ${{ parameters.wizContainerpolicyHitsOnly }}
    wizContainerfileHashesScan: ${{ parameters.wizContainerfileHashesScan }}
    isContainerized: ${{ parameters.isContainerized }}
    dockerBuildContext: ${{ parameters.dockerBuildContext }}
    dockerRepository: ${{ parameters.dockerRepository }}
    Dockerfile: ${{ parameters.Dockerfile }}
    dockerTags: ${{ parameters.dockerTags }}
    artifactName: ${{ parameters.artifactName }}
    projectPath: ${{ parameters.projectPath }}

# ------------------------------------------------------------
# Stage 4: Release Tagging
# ------------------------------------------------------------

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: ../stages/release/release-tag-and-artifact.yml
    parameters:
      stageName: 'ReleaseStage'
      displayName: ${{ parameters.releasedisplayName }}
      releaseBranch: ${{ parameters.releaseBranch }} 
      releaseType: ${{ parameters.releaseType }} 
      universalFeedNameApp: ${{ parameters.universalFeedNameApp }}
      universalPackageName: ${{ parameters.universalPackageName }}

# ------------------------------------------------------------
# Stage 5: Deploy to Azure Functions
# ------------------------------------------------------------

- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
  - ${{ each env in parameters.environments }}:
    - ${{ if ne(env.name, 'prod') }}:
      - template: ../stages/deploy/deploy-on-azure-functions.yml
        parameters:
          stageName: 'Deploy_${{ env.name }}'
          stageDisplayName: 'Deploy to Azure Function App - ${{ env.name }}'
          jobName: 'DeployFunctionApp'
          jobDisplayName: 'Deploy Azure Function App'
          environment: ${{ env.name }} 
          azureSubscription:  ${{ env.azureSubscription }}
          appType: 'functionAppLinux'
          appName: ${{ env.functionAppName }} 
          artifactName: 'Build-Drop'
          universalFeedNameApp: ${{ parameters.universalFeedNameApp }}
          universalPackageName: ${{ parameters.universalPackageName }}
          universalPackageVersion: $[ stageDependencies.ReleaseStage.ReleaseJob.outputs['calversion.new_version'] ]
          packagePath: ${{ parameters.archiveFileName }}
          resourceGroupName: ${{ env.resourceGroupName }}

- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
  - ${{ each env in parameters.environments }}:
    - ${{ if eq(env.name, 'prod') }}:
      - template: ../stages/deploy/deploy-on-azure-functions.yml
        parameters:
          stageName: 'Deploy_${{ env.name }}'
          stageDisplayName: 'Deploy to Azure Function App  - ${{ env.name }}'
          jobName: 'DeployFunctionApp'
          jobDisplayName: 'Deploy Azure Function App'
          environment: ${{ env.name }} 
          azureSubscription:  ${{ env.azureSubscription }}
          appType: 'functionAppLinux'
          appName: ${{ env.functionAppName }} 
          artifactName: 'Build-Drop'
          universalFeedNameApp: ${{ parameters.universalFeedNameApp }}
          universalPackageName: ${{ parameters.universalPackageName }}
          universalPackageVersion: $[ stageDependencies.ReleaseStage.ReleaseJob.outputs['calversion.new_version'] ]
          packagePath: ${{ parameters.archiveFileName }}
          resourceGroupName: ${{ env.resourceGroupName }}

# ------------------------------------------------------------
# Stage 6: Log Collection
# ------------------------------------------------------------

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: ../stages/logs/collect-logs.yml
    parameters:
      logUniversalFeedName: ${{ parameters.logUniversalFeedName }}
      logsPackageName: ${{ parameters.universalPackageName }}-pipeline-logs
      packageDescription: 'Pipeline Logs for ${{ parameters.universalPackageName }}'