parameters:
  - name: stageName
    type: string
    default: 'Deploy'

  - name: stageDisplayName
    type: string
    default: 'Deploy to Azure Web App'

  - name: jobName
    type: string
    default: 'DeployWebApp'

  - name: jobDisplayName
    type: string
    default: 'Deploy Azure Web App'

  - name: environment
    type: string
    default: ''

  - name: azureSubscription
    type: string
    default: ''

  - name: resourceGroupName
    type: string
    default: ''

  - name: appName
    type: string
    default: ''

  - name: appOs             # windows | linux
    type: string
    default: 'linux'

  - name: artifactName
    type: string
    default: 'Build-Drop'

  - name: packagePath
    type: string
    default: '$(Pipeline.Workspace)/Build-Drop/$(Build.SourceVersion).zip'

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageDisplayName }}

  jobs:
  - deployment: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobDisplayName }}
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:

          # Download promoted artifact
          - download: current
            artifact: ${{ parameters.artifactName }}
            displayName: Download Artifact

          # ============================
          # Windows Web App
          # ============================
          - task: AzureWebApp@1
            displayName: Deploy Windows Web App
            condition: eq('${{ parameters.appOs }}', 'windows')
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              appType: 'webApp'
              appName: ${{ parameters.appName }}
              package: ${{ parameters.packagePath }}

          # ============================
          # Linux Web App
          # ============================
          - task: AzureWebApp@1
            displayName: Deploy Linux Web App
            condition: eq('${{ parameters.appOs }}', 'linux')
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              resourceGroupName: ${{ parameters.resourceGroupName }}
              appType: 'webAppLinux'
              appName: ${{ parameters.appName }}
              package: ${{ parameters.packagePath }}
